---
name: cmpsc-302-spring-2019-lab2
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    travels.html:
        --fragment "<title>Share Your Travels</title>" --count 1 --exact
        --fragment "<h1>Share Your Travels</h1>" --count 1 --exact
        --fragment "<h3>Reviews</h3>" --count 1 --exact
        --fragment "<p>" --count 4 --exact
        --fragment "<time>" --count 2 --exact
        --fragment "<div>" --count 2 --exact
        --fragment "<html>" --count 1 --exact
        --fragment "<head>" --count 1 --exact
        --fragment "<body>" --count 1 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 3 --exact
    --words 100
# --> check the submission image exists
images/travels_submission.png:
    --exists
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/travels.html" --executes
--command "htmlhint src/www/travels.html" --count 1 --exact
--command "htmlhint src/www/travels.html" --fragment "no errors found" --count 1 --exact
